### ISSUE TITLE
Preprocess the data with data_sim/raw/prepare_data.py

### ISSUE THREAD

**Issue by yiyi9527** [yaochenzhu/PSF-VAE#1]
For step to process Data “Preprocess the data with data_sim/raw/prepare_data.py”, I can't find a folder like this in all files...So HELP kids TT

**Comment by yiyi9527** [comment]
And in other Steps, there still have the same question, like I can't find the command file "prepare_data.py" "simulate.py" "preprocess.py" "eval.py" and "summarize.py", HOPE good people helps, pls, TT

**Comment by yaochenzhu** [comment]
Hi Yiyi,

Thank you for contacting me for the missing file.
I've upload the data simulation codes in the data_simulation folder.

Best,
Yaochen
